
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8300

spring:
  application:
    name: zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: feign